version: '3' # версия синтаксиса
services:
  express-app: # Сервер Express
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - react-app
    environment:
      DATABASE_URL: 'mongodb+srv://poster:PuYC7eZv9JwhSLvY@cluster0.zoj4t.mongodb.net/poster?retryWrites=true&w=majority&appName=Cluster0'

  react-app: # React-приложение
      build: ../poster-react # Путь к вашему React-приложению относительно корня вашего проекта
      ports:
        - '80:80' # Порт, на котором будет доступно ваше React-приложение
        - '8000:8000' # Порт, на котором будет доступно ваше React-приложение
volumes:
  react_app: # Объявление именованного тома